/** Seed source only — app pages read the database, not this file. */
import type { Bundle, BundleItem, Category, Product } from "@/lib/types";

const g = {
  rose: (a: string, b = "#C98F86") => `linear-gradient(145deg, ${a}, ${b})`,
  sage: (a: string, b = "#9CA88B") => `linear-gradient(145deg, ${a}, ${b})`,
  clay: (a: string, b = "#B99A88") => `linear-gradient(145deg, ${a}, ${b})`,
  dust: (a: string, b = "#CBA79C") => `linear-gradient(145deg, ${a}, ${b})`,
};

export const categories: Category[] = [
  {
    id: "c1",
    name: "Wall & Light Décor",
    slug: "lighting",
    description:
      "Fairy lights, peel-stick LEDs, and rolled posters — the small glows that make a room feel held.",
    image: g.rose("#EADFC9"),
  },
  {
    id: "c2",
    name: "Desk / Table Décor",
    slug: "desk",
    description:
      "Trays, frames, lamps, and organizers for the desk you're finally ready to make yours.",
    image: g.clay("#E8DACB"),
  },
  {
    id: "c3",
    name: "Cozy / Soft Décor",
    slug: "cozy",
    description:
      "Candles, holders, and 16×16 cushion covers — the soft layer that makes a room feel finished.",
    image: g.dust("#E3D5CC"),
  },
  {
    id: "c4",
    name: "Greenery",
    slug: "greenery",
    description:
      "Artificial plants and stems that stay pretty without the watering guilt. No glass vases.",
    image: g.sage("#DCE2CE"),
  },
  {
    id: "c5",
    name: "Organization",
    slug: "organization",
    description:
      "Makeup trays, jewelry boxes, and small baskets — practical pieces that still look like décor.",
    image: g.clay("#E2D6C5"),
  },
];

export const products: Product[] = [
  {
    id: "p1",
    name: "Warm Glow Fairy Lights",
    slug: "warm-glow-fairy-lights",
    shortDescription: "A small light that makes a big room feel held.",
    description:
      "Battery-operated string lights in a warm amber tone. Drape them over a headboard, a desk edge, or a corner you want to come home to. Lightweight, unbreakable, and easy to restock.",
    categoryId: "c1",
    price: 799,
    costPrice: 320,
    stockQty: 48,
    weight: 180,
    images: [g.rose("#EADFC9"), g.clay("#E8DACB"), g.dust("#E3D5CC")],
    status: "active",
  },
  {
    id: "p2",
    name: "Soft White String Lights",
    slug: "soft-white-string-lights",
    shortDescription: "Quieter light for late-night study or slow mornings.",
    description:
      "A cooler, softer white than our warm glow strand — better if your room already runs golden. Same easy battery pack, same no-fuss hang.",
    categoryId: "c1",
    price: 849,
    costPrice: 330,
    stockQty: 36,
    weight: 180,
    images: [g.sage("#E5DED0"), g.rose("#EADFC9"), g.clay("#D9CBBA")],
    status: "active",
  },
  {
    id: "p3",
    name: "Peel-Stick LED Strip Lights",
    slug: "peel-stick-led-strip",
    shortDescription: "A glow-up for the shelf, the bed frame, the forgotten ledge.",
    description:
      "Cut-to-fit LED strip with a peel-and-stick back. Made for the aesthetic-corner trend: under a shelf, behind a monitor, along a skirting board. No electrician, no nails.",
    categoryId: "c1",
    price: 1299,
    costPrice: 480,
    stockQty: 28,
    weight: 220,
    images: [g.rose("#DCCFC0"), g.sage("#D2D9C4"), g.clay("#E8DACB")],
    status: "active",
  },
  {
    id: "p4",
    name: "Acrylic Mini Mirror",
    slug: "acrylic-mini-mirror",
    shortDescription: "A small reflection that won't shatter in transit.",
    description:
      "Acrylic, not glass — chosen on purpose so it survives a Pakistan courier run. Lean it on a tray or stick it in a glow-up corner. One of the few mirrors we'll carry at launch.",
    categoryId: "c1",
    price: 899,
    costPrice: 340,
    stockQty: 22,
    weight: 260,
    images: [g.dust("#E3D5CC"), g.clay("#E2D6C5"), g.rose("#EADFC9")],
    status: "active",
  },
  {
    id: "p5",
    name: "Rolled Line-Art Poster",
    slug: "rolled-line-art-poster",
    shortDescription: "A quiet figure, shipped rolled — not framed, not fragile.",
    description:
      "Single-line figure on warm off-white stock. Ships rolled in a tube so it doesn't crack in transit. Frame it yourself later, or pin it as-is for a hostel-friendly hang.",
    categoryId: "c1",
    price: 650,
    costPrice: 180,
    stockQty: 60,
    weight: 90,
    images: [g.clay("#E2D6C5"), g.dust("#D9C7C2"), g.rose("#EADFC9")],
    status: "active",
  },
  {
    id: "p6",
    name: "Rolled Botanic Poster",
    slug: "rolled-botanic-poster",
    shortDescription: "A single stem, drawn soft. Pairs with the line-art print.",
    description:
      "Minimal botanic study in sage and bone. Same rolled-tube shipping as the line-art poster — two together make a wall feel considered without a gallery of frames.",
    categoryId: "c1",
    price: 650,
    costPrice: 180,
    stockQty: 60,
    weight: 90,
    images: [g.sage("#DCE2CE"), g.clay("#E2D6C5"), g.dust("#E3D5CC")],
    status: "active",
  },
  {
    id: "p7",
    name: "Desk Organizer Set",
    slug: "desk-organizer-set",
    shortDescription: "Everything your desk needs to stop looking borrowed.",
    description:
      "A three-piece resin-and-wood set: pen cup, tray, and a small upright for notes. Made for a study desk that has to work and still look like you.",
    categoryId: "c2",
    price: 1450,
    costPrice: 620,
    stockQty: 24,
    weight: 540,
    images: [g.clay("#E8DACB"), g.rose("#EADFC9"), g.sage("#DCE2CE")],
    status: "active",
  },
  {
    id: "p8",
    name: "Mini LED Desk Lamp",
    slug: "mini-led-desk-lamp",
    shortDescription: "A pool of light just for the page, not the whole room.",
    description:
      "Compact warm-white lamp with a weighted base. Small enough for a hostel desk, bright enough for late assignments. USB-powered.",
    categoryId: "c2",
    price: 1299,
    costPrice: 510,
    stockQty: 20,
    weight: 410,
    images: [g.rose("#EADFC9"), g.clay("#E8DACB"), g.dust("#E3D5CC")],
    status: "active",
  },
  {
    id: "p9",
    name: "Acrylic Photo Frame",
    slug: "acrylic-photo-frame",
    shortDescription: "A 4×6 that doesn't pretend to be marble.",
    description:
      "Clear acrylic, thin profile, for a print you actually love. Light to ship, hard to break. Works on a desk or a gifting bundle.",
    categoryId: "c2",
    price: 750,
    costPrice: 240,
    stockQty: 40,
    weight: 160,
    images: [g.dust("#E3D5CC"), g.sage("#DCE2CE"), g.clay("#E2D6C5")],
    status: "active",
  },
  {
    id: "p10",
    name: "Resin Catchall Tray",
    slug: "resin-catchall-tray",
    shortDescription: "Keys, rings, the hair clip you always lose.",
    description:
      "Small terrazzo-speckled resin tray. Sits on a dresser or a glow-up corner and makes the mess look intentional.",
    categoryId: "c2",
    price: 950,
    costPrice: 360,
    stockQty: 32,
    weight: 280,
    images: [g.clay("#E8DACB"), g.dust("#CBA79C"), g.rose("#EADFC9")],
    status: "active",
  },
  {
    id: "p11",
    name: "Mini Terrazzo Vase",
    slug: "mini-terrazzo-vase",
    shortDescription: "A vase-alternative in resin — no glass, no breakage story.",
    description:
      "Resin, not glass. Sized for a few stems or to stand empty as a sculptural bit on a shelf. The Cozy Room bundle's quiet centerpiece.",
    categoryId: "c2",
    price: 1150,
    costPrice: 420,
    stockQty: 26,
    weight: 310,
    images: [g.sage("#DCE2CE"), g.clay("#E8DACB"), g.dust("#E3D5CC")],
    status: "active",
  },
  {
    id: "p12",
    name: "Vanilla Amber Candle",
    slug: "vanilla-amber-candle",
    shortDescription: "The one people reorder when it burns down.",
    description:
      "A warm vanilla-amber pour in a reusable tin. Burns clean enough for a small room. The glue in more than one of our bundles — and the easiest thing to gift.",
    categoryId: "c3",
    price: 950,
    costPrice: 310,
    stockQty: 55,
    weight: 240,
    images: [g.dust("#E3D5CC"), g.rose("#EADFC9"), g.clay("#E8DACB")],
    status: "active",
  },
  {
    id: "p13",
    name: "Sandalwood Cedar Candle",
    slug: "sandalwood-cedar-candle",
    shortDescription: "Drier, woodier — for desks that shouldn't smell like dessert.",
    description:
      "Sandalwood and cedar in the same tin format as Vanilla Amber. If you study at this desk, this is the one.",
    categoryId: "c3",
    price: 950,
    costPrice: 310,
    stockQty: 40,
    weight: 240,
    images: [g.clay("#E8DACB"), g.sage("#DCE2CE"), g.dust("#E3D5CC")],
    status: "active",
  },
  {
    id: "p14",
    name: "Speckled Candle Holder",
    slug: "speckled-candle-holder",
    shortDescription: "A small ceramic-look seat for a tin or a taper.",
    description:
      "Matte speckled holder in bone and clay. Sized for our tins and for a slim taper if you already have one. Ships without the candle.",
    categoryId: "c3",
    price: 699,
    costPrice: 220,
    stockQty: 30,
    weight: 200,
    images: [g.clay("#E2D6C5"), g.dust("#E3D5CC"), g.sage("#D9CBBA")],
    status: "active",
  },
  {
    id: "p15",
    name: "Linen Cushion Cover — Dusty Rose",
    slug: "linen-cushion-dusty-rose",
    shortDescription: "16×16, the standard size, in a muted rose.",
    description:
      "Washed linen-look cover, 16×16, envelope close. We sell the cover only — use a cushion you already have. Dusty rose against bone bedding or a grey hostel blanket.",
    categoryId: "c3",
    price: 850,
    costPrice: 280,
    stockQty: 34,
    weight: 150,
    images: [g.dust("#E3D5CC"), g.rose("#D9C7C2"), g.clay("#E8DACB")],
    status: "active",
  },
  {
    id: "p16",
    name: "Linen Cushion Cover — Sage",
    slug: "linen-cushion-sage",
    shortDescription: "The same 16×16 cover, in muted sage.",
    description:
      "Pair it with the dusty rose or let it sit alone on a study chair. Same envelope close, same wash-and-done care.",
    categoryId: "c3",
    price: 850,
    costPrice: 280,
    stockQty: 34,
    weight: 150,
    images: [g.sage("#DCE2CE"), g.clay("#E2D6C5"), g.dust("#E3D5CC")],
    status: "active",
  },
  {
    id: "p17",
    name: "Mini Potted Succulent",
    slug: "mini-potted-succulent",
    shortDescription: "A plant that doesn't ask you to remember it.",
    description:
      "PU succulent in a small matte pot. Made for a study desk or a bathroom shelf. Unbreakable pot, no watering schedule.",
    categoryId: "c4",
    price: 799,
    costPrice: 260,
    stockQty: 38,
    weight: 190,
    images: [g.sage("#DCE2CE"), g.clay("#E8DACB"), g.rose("#EADFC9")],
    status: "active",
  },
  {
    id: "p18",
    name: "Artificial Olive Stem",
    slug: "artificial-olive-stem",
    shortDescription: "One stem. Enough for a bottle, a jar, a quiet shelf.",
    description:
      "A single olive-leaf stem in muted green. Lean it in the terrazzo vase or a jar you already own. Ships flat.",
    categoryId: "c4",
    price: 650,
    costPrice: 190,
    stockQty: 44,
    weight: 80,
    images: [g.sage("#D2D9C4"), g.clay("#E2D6C5"), g.dust("#E3D5CC")],
    status: "active",
  },
  {
    id: "p19",
    name: "Small Potted Fern",
    slug: "small-potted-fern",
    shortDescription: "A little more leaf than the succulent, same zero-care deal.",
    description:
      "Artificial fern in a bone pot. Softens a minimal room without asking for a window.",
    categoryId: "c4",
    price: 899,
    costPrice: 300,
    stockQty: 28,
    weight: 230,
    images: [g.sage("#DCE2CE"), g.rose("#EADFC9"), g.clay("#E8DACB")],
    status: "active",
  },
  {
    id: "p20",
    name: "Soft Pink Flower Stems",
    slug: "soft-pink-flower-stems",
    shortDescription: "A handful of stems, not a bouquet that will wilt by Friday.",
    description:
      "Three artificial stems in dusty pink. Sit them in the mini vase or leave them on a book. The Cozy Room bundle's only floral.",
    categoryId: "c4",
    price: 750,
    costPrice: 220,
    stockQty: 36,
    weight: 90,
    images: [g.dust("#E3D5CC"), g.rose("#D9C7C2"), g.sage("#DCE2CE")],
    status: "active",
  },
  {
    id: "p21",
    name: "Makeup Organizer Tray",
    slug: "makeup-organizer-tray",
    shortDescription: "Compartments that look like a tray, not a toolbox.",
    description:
      "Open acrylic-and-resin tray with four wells. For the girl whose vanity is also her desk.",
    categoryId: "c5",
    price: 1350,
    costPrice: 520,
    stockQty: 22,
    weight: 380,
    images: [g.dust("#E3D5CC"), g.clay("#E8DACB"), g.rose("#EADFC9")],
    status: "active",
  },
  {
    id: "p22",
    name: "Jewelry Box — Soft Linen",
    slug: "jewelry-box-soft-linen",
    shortDescription: "A quiet box for the pieces you actually wear.",
    description:
      "Linen-wrapped box with a soft insert. Small enough for a drawer, finished enough to leave out. One of the few items that can sit at the higher end of our range.",
    categoryId: "c5",
    price: 1699,
    costPrice: 640,
    stockQty: 16,
    weight: 420,
    images: [g.clay("#E2D6C5"), g.dust("#E3D5CC"), g.sage("#DCE2CE")],
    status: "active",
  },
  {
    id: "p23",
    name: "Woven Storage Basket",
    slug: "woven-storage-basket",
    shortDescription: "For the things that don't have a home yet.",
    description:
      "Small seagrass-look basket. Throws, chargers, the scarf on the chair. Looks like décor even when it's full.",
    categoryId: "c5",
    price: 1199,
    costPrice: 430,
    stockQty: 20,
    weight: 310,
    images: [g.clay("#E8DACB"), g.sage("#D9CBBA"), g.dust("#E3D5CC")],
    status: "active",
  },
  {
    id: "p24",
    name: "Desktop Storage Boxes",
    slug: "desktop-storage-boxes",
    shortDescription: "A pair of boxes that make a pile look like a set.",
    description:
      "Two nested paperboard boxes in bone and clay. For stationery, tea bags, the bits that clutter a gifting-ready desk.",
    categoryId: "c5",
    price: 999,
    costPrice: 340,
    stockQty: 30,
    weight: 250,
    images: [g.clay("#E2D6C5"), g.rose("#EADFC9"), g.dust("#E3D5CC")],
    status: "active",
  },
];

export const bundles: Bundle[] = [
  {
    id: "b1",
    name: "Cozy Room Bundle",
    slug: "cozy-room-bundle",
    description:
      "Fairy lights, a rolled poster, the terrazzo vase, stems, and a vanilla-amber candle. The hostel-room reset.",
    bundlePrice: 3499,
    image: "linear-gradient(140deg, #E5DBC9, #C98F86)",
  },
  {
    id: "b2",
    name: "Study Desk Bundle",
    slug: "study-desk-bundle",
    description:
      "Organizer, mini plant, sandalwood candle, frame, and a small lamp. Everything a desk needs to feel like yours.",
    bundlePrice: 4299,
    image: "linear-gradient(140deg, #DCE2CE, #9CA88B)",
  },
  {
    id: "b3",
    name: "Minimal Room Bundle",
    slug: "minimal-room-bundle",
    description:
      "Two posters, a potted fern, and a candle. Enough to quiet a room without filling it.",
    bundlePrice: 2499,
    image: "linear-gradient(140deg, #E3D5CC, #B99A88)",
  },
  {
    id: "b4",
    name: "Glow-Up Corner Bundle",
    slug: "glow-up-corner-bundle",
    description:
      "LED strip, acrylic mini mirror, a catchall tray, and fairy lights — for the corner you keep photographing.",
    bundlePrice: 3199,
    image: "linear-gradient(140deg, #D9C7C2, #C98F86)",
  },
  {
    id: "b5",
    name: "Gifting Bundle",
    slug: "gifting-bundle",
    description:
      "Candle, desktop boxes, and a photo frame. The secondary-audience gift that still feels like Lunora.",
    bundlePrice: 2199,
    image: "linear-gradient(140deg, #E8DACB, #CBA79C)",
  },
];

export const bundleItems: BundleItem[] = [
  { id: "bi1", bundleId: "b1", productId: "p1", quantity: 1 },
  { id: "bi2", bundleId: "b1", productId: "p5", quantity: 1 },
  { id: "bi3", bundleId: "b1", productId: "p11", quantity: 1 },
  { id: "bi4", bundleId: "b1", productId: "p20", quantity: 1 },
  { id: "bi5", bundleId: "b1", productId: "p12", quantity: 1 },
  { id: "bi6", bundleId: "b2", productId: "p7", quantity: 1 },
  { id: "bi7", bundleId: "b2", productId: "p17", quantity: 1 },
  { id: "bi8", bundleId: "b2", productId: "p13", quantity: 1 },
  { id: "bi9", bundleId: "b2", productId: "p9", quantity: 1 },
  { id: "bi10", bundleId: "b2", productId: "p8", quantity: 1 },
  { id: "bi11", bundleId: "b3", productId: "p5", quantity: 1 },
  { id: "bi12", bundleId: "b3", productId: "p6", quantity: 1 },
  { id: "bi13", bundleId: "b3", productId: "p19", quantity: 1 },
  { id: "bi14", bundleId: "b3", productId: "p12", quantity: 1 },
  { id: "bi15", bundleId: "b4", productId: "p3", quantity: 1 },
  { id: "bi16", bundleId: "b4", productId: "p4", quantity: 1 },
  { id: "bi17", bundleId: "b4", productId: "p10", quantity: 1 },
  { id: "bi18", bundleId: "b4", productId: "p1", quantity: 1 },
  { id: "bi19", bundleId: "b5", productId: "p12", quantity: 1 },
  { id: "bi20", bundleId: "b5", productId: "p24", quantity: 1 },
  { id: "bi21", bundleId: "b5", productId: "p9", quantity: 1 },
];
